#!/bin/bash

which pdflatex || brew cask install basictex
which cargo-watch || cargo install cargo-watch

cargo watch \
  --watch report/report.tex \
  --clear \
  --shell 'cd report; bibtex report; cd ..; pdflatex -output-directory report report/report.tex'
