#!/bin/bash

# Counts the total number of calls made to Cadical. Each time the algorithm runs
# it is called multiple times through its incremental interface.

optimums=$(cat evaluate/measurements/* | grep ^o | wc -l)
finals=$(ls evaluate/measurements/* | wc -l)

echo "$(($optimums + $finals)) calls were made to cadical"
