#!/usr/bin/env ruby

# Counts the total number of calls made to Cadical. Each time the algorithm runs
# it is called multiple times through its incremental interface.

count = 0

Dir.glob("evaluate/measurements/*").each do |path|
  File.read(path).lines.each do |line|
    count += 1 if line.start_with?("o")
  end

  count += 1
end

puts "#{count} calls were made to cadical"
