#!/bin/bash

# Fetch a set of uniform random 3-SAT instances from this page:
# https://www.cs.ubc.ca/~hoos/SATLIB/benchm.html

wget https://www.cs.ubc.ca/~hoos/SATLIB/Benchmarks/SAT/RND3SAT/uf100-430.tar.gz
tar xvfz uf100-430.tar.gz && \
ls *.cnf | xargs -n1 sed -i '' '/%/{N;N;d;}' && \
mkdir -p evaluate/benchmarks && \
mv *.cnf evaluate/benchmarks && \
rm uf100*
