#!/bin/bash

# Copy benchmarks that are satisfiable into a subdirectory. Uses cadical to
# determine satisfiability with a given timeout. Defaults to 300 seconds.

timeout=${1:-300}

mkdir -p evaluate/benchmarks/satisfiable

for file in evaluate/benchmarks/*.xz; do
  cadical -t $timeout --quiet $file

  if [ $? -eq 10 ]; then
    cp $file evaluate/benchmarks/satisfiable/
  fi
done
