#!/bin/bash

# Runs the k-flip algorithm for different values of k on each of the satisfiable
# benchmarks. Writes output to a set of files. k ranges from 0 to 25 by default.

max_k=${1:-20}
runs=${2:-5}

mkdir -p evaluate/measurements

for file in evaluate/benchmarks/satisfiable/*.cnf; do
  for k in $(seq 0 $max_k); do
    for r in $(seq 1 $runs); do
      outfile="evaluate/measurements/$(basename $file)-k=$k-run=$r.txt"
      cargo run $k < $file > $outfile
    done
  done
done
